version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      TZ: 'GMT'
      PGTZ: 'GMT'
    ports:
      - '5432:5432'
    volumes:
      - postgres:/data/postgres
      - ./apps/api/init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    env_file:
      - apps/api/.env

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_net
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq

  redis:
    container_name: redis
    image: redis/redis-stack:latest
    command: redis-server --requirepass password
    restart: on-failure
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
    networks:
      - redis_net

  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: semitechnologies/weaviate:1.23.9
    ports:
      - '8080:8080'
      - '50051:50051'
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: always
    environment:
      IMAGE_INFERENCE_API: 'http://i2v-neural:8080'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'img2vec-neural'
      ENABLE_MODULES: 'img2vec-neural'
      CLUSTER_HOSTNAME: 'node1'
  i2v-neural:
    image: semitechnologies/img2vec-pytorch:resnet50
    environment:
      ENABLE_CUDA: '0'

volumes:
  redis:
  weaviate_data:
  postgres:

networks:
  rabbitmq_net:
    driver: bridge
  redis_net:
    driver: bridge
  postgres_net:
    driver: bridge
