export const ROUTES = {
  AUTH: 'auth',
  HEALTH: 'health',
  METRICS: 'metrics',
  NOTIFICATIONS: 'notifications',
  USERS: 'users',
  CARTS: 'carts',
  CATEGORIES: 'categories',
  IMAGES_GENERATE: 'images/generate',
  IMAGES: 'images',
  ORDERS: 'orders',
  PAYMENTS: 'payments',
  PRODUCTS: 'products',
  REVIEWS: 'reviews',
  SELLERS: 'sellers',
  TASKS: 'tasks',
  ADDRESSES: 'addresses',
  WORKSPACES: 'workspaces',
  CREDITS: 'credits',
  PLANS: 'plans',
  AI_SUGGESTS: 'ai-suggests',
};
