FROM --platform=linux/amd64 node:18.16.1-slim

RUN apt-get update && \
    apt-get install -y build-essential libpq-dev openssl

RUN npm install -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY . .

RUN pnpm nx run api:prisma-generate

ENV NODE_ENV=production

RUN pnpm nx run api:build

CMD [ "node", "dist/apps/api/main.js" ]
